markdown: kramdown

description: Jayaraj's resume
title: Jayaraj's resume

highlighter: rouge

googleverify: gC8gMLC1UpPDYi2y5KR_9Sq79n4TYMiQM7UcSvtyfms
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']